(() => {
  // Exported artwork has a fixed palette independent of the surrounding app theme.
  function render(kind, save, snapshot, targets, artworks, label) {
    const canvas = document.createElement('canvas'), profile = save.profile || {};
    canvas.width = 1080;
    canvas.height = kind === 'b30' ? 420 + Math.ceil(snapshot.phi.length / 2) * 178 + Math.ceil(snapshot.best27.length / 2) * 178 : 1420;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#10251d';ctx.fillRect(0, 0, canvas.width, canvas.height);
    function text(value, x, y, size = 24, color = '#d7ffe8', max = 930) {
      ctx.font = `500 ${size}px sans-serif`;ctx.fillStyle = color;
      let content = String(value), shortened = false;
      while (content.length && ctx.measureText(content + (shortened ? '…' : '')).width > max) {content = content.slice(0, -1);shortened = true;}
      ctx.fillText(content + (shortened ? '…' : ''), x, y);
    }
    text(profile.playerId || label || 'Phigros Player', 48, 88, 48);
    text(`${snapshot.overall.toFixed(4)} RKS · ${kind === 'b30' ? 'P3 + B27' : '个人信息'}`, 48, 142, 30, '#9ed8bd');
    let artworkIndex = 0;
    function card(record, index, y) {
      const x = 48 + (index % 2) * 500, top = y + Math.floor(index / 2) * 178;
      ctx.fillStyle = '#1d392d';ctx.fillRect(x, top, 484, 162);
      const artwork = artworks[artworkIndex++];if (artwork) ctx.drawImage(artwork.image, x + 12, top + 12, 76, 76);
      const titleX = artwork ? x + 100 : x + 12, titleWidth = artwork ? 368 : 460;
      text(`${index + 1}. ${record.title || record.id}`, titleX, top + 34, 24, '#d7ffe8', titleWidth);
      text(`${record.level} ${Number(record.constant).toFixed(1)} · ${phigrosPresentation.grade(record)}`, titleX, top + 68, 23, '#9ed8bd', titleWidth);
      text(`${Number(record.score).toLocaleString()} · ${Number(record.accuracy).toFixed(4)}%`, x + 12, top + 115, 23, '#d7ffe8', 460);
      const identity = phigrosRks.identity(record);
      const target = targets[identity] || (targets[identity] = phigrosRks.pushTarget(record, save.records, snapshot));
      const push = target.targetAccuracy == null ? (record.accuracy >= 100 ? '已达 Phi' : '无法推分') : `推分 ${target.targetAccuracy.toFixed(4)}%`;
      text(`${record.rks.toFixed(4)} RKS · ${push}`, x + 12, top + 147, 21, '#9ed8bd', 460);
    }
    if (kind === 'b30') {
      text('P3', 48, 206, 30);snapshot.phi.forEach((record, index) => card(record, index, 230));
      const base = 280 + Math.ceil(snapshot.phi.length / 2) * 178;
      text('B27', 48, base, 30);snapshot.best27.forEach((record, index) => card(record, index, base + 24));
    } else {
      text(`课题模式 ${Math.floor((profile.challengeModeRank || 0) / 100)} / ${(profile.challengeModeRank || 0) % 100}`, 48, 214, 30);
      const units = ['KiB', 'MiB', 'GiB', 'TiB', 'PiB'];
      const money = (profile.money || []).map((value, index) => value > 0 ? `${value} ${units[index] || '?'}` : '').filter(Boolean).reverse().join(' · ') || '0 KiB';
      text(`Data ${money}`, 48, 262, 26, '#9ed8bd');
      text('难度统计', 48, 328, 30);
      ['EZ', 'HD', 'IN', 'AT'].forEach((level, index) => text(`${level}     Clear ${profile.cleared?.[index] || 0}     FC ${profile.fullCombo?.[index] || 0}     Phi ${profile.phi?.[index] || 0}`, 48, 378 + index * 42, 26));
      text('Top Records', 48, 574, 30);snapshot.sorted.slice(0, 8).forEach((record, index) => card(record, index, 604));
    }
    text(`Generated by Phigros Data Studio ${phigrosBuild.version}`, 48, canvas.height - 36, 22, '#9ed8bd');
    return canvas;
  }
  window.phigrosImages = {render};
})();
