(() => {
  const clientId='rAK3FfdieFob2Nn8Am';
  const config=server=>server==='GLOBAL'?{appId:'kviehleldgxsagpozb',appKey:'tG9CTm0LDD736k9HMM9lBZrbeBGRmUkjSfNLDNib',base:'https://kviehlel.cloud.ap-sg.tapapis.com/1.1',accounts:'https://accounts.tapapis.com',open:'https://open.tapapis.com'}:{appId:'rAK3FfdieFob2Nn8Am',appKey:'Qr9AEqtuoSVS3zeD6iVbM4ZC0AtkJcQ89tywVyi0',base:'https://rak3ffdi.cloud.tds1.tapapis.cn/1.1',accounts:'https://accounts.tapapis.cn',open:'https://open.tapapis.cn'};
  const form=value=>new TextEncoder().encode(Object.entries(value).map(([key,item])=>`${encodeURIComponent(key)}=${encodeURIComponent(item)}`).join('&'));
  async function postForm(url,value){const response=await ats.request(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form(value)});let root={};try{root=response.text?JSON.parse(response.text):{};}catch(_){throw new Error(`TapTap 返回了无法识别的数据（HTTP ${response.status}）`);}return{status:response.status,root};}
  function md5(input){const bytes=new TextEncoder().encode(input),length=bytes.length,total=(((length+8)>>6)+1)*64,data=new Uint8Array(total);data.set(bytes);data[length]=128;new DataView(data.buffer).setUint32(total-8,length*8,true);const shifts=[7,12,17,22,5,9,14,20,4,11,16,23,6,10,15,21],k=Array.from({length:64},(_,i)=>Math.floor(Math.abs(Math.sin(i+1))*2**32)>>>0);let a0=0x67452301,b0=0xefcdab89,c0=0x98badcfe,d0=0x10325476,view=new DataView(data.buffer);for(let offset=0;offset<total;offset+=64){let a=a0,b=b0,c=c0,d=d0;for(let i=0;i<64;i++){let f,g;if(i<16){f=(b&c)|(~b&d);g=i;}else if(i<32){f=(d&b)|(~d&c);g=(5*i+1)%16;}else if(i<48){f=b^c^d;g=(3*i+5)%16;}else{f=c^(b|~d);g=(7*i)%16;}const temp=d,dNext=c,cNext=b,sum=(a+f+k[i]+view.getUint32(offset+g*4,true))>>>0,shift=shifts[Math.floor(i/16)*4+i%4];b=(b+((sum<<shift)|(sum>>>(32-shift))))>>>0;a=temp;d=dNext;c=cNext;}a0=(a0+a)>>>0;b0=(b0+b)>>>0;c0=(c0+c)>>>0;d0=(d0+d)>>>0;}return[a0,b0,c0,d0].map(value=>[0,8,16,24].map(shift=>(value>>>shift&255).toString(16).padStart(2,'0')).join('')).join('');}
  async function hmacSha1(key,value){const imported=await crypto.subtle.importKey('raw',new TextEncoder().encode(key),{name:'HMAC',hash:'SHA-1'},false,['sign']);return btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign('HMAC',imported,new TextEncoder().encode(value)))));}
  async function request(server){const cfg=config(server),deviceId=crypto.randomUUID().replace(/-/g,''),response=await postForm(`${cfg.accounts}/oauth2/v1/device/code`,{client_id:clientId,response_type:'device_code',scope:'public_profile',version:'2.1',platform:'unity',info:JSON.stringify({device_id:deviceId})}),data=response.root.data||response.root;if(!data.device_code||!data.qrcode_url)throw new Error(data.error||'TapTap 未返回登录链接');return{server,deviceId,deviceCode:data.device_code,loginUrl:data.qrcode_url,expiresAt:Date.now()+Math.max(30,Number(data.expires_in||300))*1000,intervalSeconds:Math.max(1,Math.min(10,Number(data.interval||2)))};}
  async function mac(url,token){const parsed=new URL(url),timestamp=String(Math.floor(Date.now()/1000)).padStart(10,'0'),nonce=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(16)))),path=parsed.pathname+parsed.search,port=parsed.port||'443',signature=await hmacSha1(token.mac_key,`${timestamp}\n${nonce}\nGET\n${path}\n${parsed.hostname}\n${port}\n\n`);return`MAC id="${token.kid}", ts="${timestamp}", nonce="${nonce}", mac="${signature}"`;}
  async function poll(login){if(Date.now()>=login.expiresAt)throw new Error('TapTap 登录链接已过期');const cfg=config(login.server),response=await postForm(`${cfg.accounts}/oauth2/v1/token`,{grant_type:'device_token',client_id:clientId,secret_type:'hmac-sha-1',code:login.deviceCode,version:'1.0',platform:'unity',info:JSON.stringify({device_id:login.deviceId})}),token=response.root.data||response.root;if(!token.mac_key||!token.kid){const error=token.error||response.root.error||'';if(['','authorization_pending','authorization_waiting','slow_down'].includes(error))return null;throw new Error(`TapTap 登录失败：${error}`);}const profileUrl=`${cfg.open}/account/profile/v1?client_id=${clientId}`,profileResponse=await ats.request(profileUrl,{headers:{Authorization:await mac(profileUrl,token)}});if(profileResponse.status<200||profileResponse.status>=300)throw new Error(`TapTap 账号信息读取失败（HTTP ${profileResponse.status}）`);const profileRoot=JSON.parse(profileResponse.text||'{}'),auth={...(profileRoot.data||profileRoot),...token},now=Math.floor(Date.now()/1000),sign=`${md5(`${now}${cfg.appKey}`)},${now}`,body=new TextEncoder().encode(JSON.stringify({authData:{taptap:auth}})),lean=await ats.request(`${cfg.base}/users`,{method:'POST',headers:{'Content-Type':'application/json','X-LC-Id':cfg.appId,'X-LC-Sign':sign},body}),root=JSON.parse(lean.text||'{}');if(lean.status<200||lean.status>=300)throw new Error(root.error||`LeanCloud 登录失败（HTTP ${lean.status}）`);if(!/^[A-Za-z0-9]{25}$/.test(root.sessionToken||''))throw new Error('LeanCloud 未返回 SessionToken');return{token:root.sessionToken,label:(profileRoot.data||profileRoot).name||'TapTap 账号'};}
  window.phigrosLogin={request,poll,md5};
})();
