(() => {
  const keyBytes=new Uint8Array([232,150,154,210,165,64,37,155,151,145,144,139,136,230,191,3,30,109,33,149,110,250,214,138,80,221,85,214,122,176,146,75]);
  const iv=new Uint8Array([42,79,240,138,200,13,99,7,0,87,197,149,24,200,50,83]);
  class Cursor{constructor(bytes){this.bytes=bytes;this.position=0;this.view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);}ensure(size){if(this.position+size>this.bytes.length)throw new Error('存档数据不完整');}byte(){this.ensure(1);return this.bytes[this.position++];}short(){this.ensure(2);const value=this.view.getUint16(this.position,true);this.position+=2;return value;}int(){this.ensure(4);const value=this.view.getInt32(this.position,true);this.position+=4;return value;}float(){this.ensure(4);const value=this.view.getFloat32(this.position,true);this.position+=4;return value;}varint(){const first=this.byte();return first>127?(first&127)^(this.byte()<<7):first;}string(){const size=this.varint();this.ensure(size);const value=new TextDecoder().decode(this.bytes.subarray(this.position,this.position+size));this.position+=size;return value;}get remaining(){return this.bytes.length-this.position;}}
  async function decrypt(encrypted){if(encrypted.length<=1)throw new Error('存档分片为空');const key=await crypto.subtle.importKey('raw',keyBytes,{name:'AES-CBC'},false,['decrypt']);return new Uint8Array(await crypto.subtle.decrypt({name:'AES-CBC',iv},key,encrypted.subarray(1)));}
  const normalize=value=>String(value||'').trim().replace(/\.0$/,'');
  function records(bytes,catalog){const songs=new Map(catalog.map(song=>[normalize(song.id),song]));const cursor=new Cursor(bytes),count=cursor.varint(),result=[];const levels=['EZ','HD','IN','AT','LEGACY'];while(cursor.remaining>0&&result.length<count*5){const id=normalize(cursor.string());cursor.varint();const present=cursor.byte(),fcMask=cursor.byte(),song=songs.get(id);for(let levelIndex=0;levelIndex<=4;levelIndex++){if((present&(1<<levelIndex))===0)continue;const score=cursor.int(),accuracy=Math.max(0,Math.min(100,cursor.float()));if(levelIndex>=4||score<=0)continue;result.push({id,title:song?.title||id,level:levels[levelIndex],levelIndex,constant:Number(song?.constants?.[levelIndex]||0),score:Math.max(0,Math.min(1000000,score)),accuracy,fc:score>=1000000||(fcMask&(1<<levelIndex))!==0,illustrationUrl:`https://raw.githubusercontent.com/Catrong/phi-plugin-ill/main/ill/${encodeURIComponent(id)}.png`});}}return [...new Map(result.map(item=>[`${item.id}|${item.level}`,item])).values()];}
  function user(bytes){const cursor=new Cursor(bytes);cursor.byte();return{selfIntro:cursor.string(),avatar:cursor.string(),background:cursor.string()};}
  function progress(bytes){const cursor=new Cursor(bytes);cursor.byte();cursor.string();cursor.varint();return{challengeModeRank:cursor.short(),money:Array.from({length:5},()=>cursor.varint())};}
  function summary(encoded){try{if(!encoded)return{};const bytes=Uint8Array.from(atob(encoded),value=>value.charCodeAt(0)),cursor=new Cursor(bytes);cursor.byte();const value={challengeModeRank:cursor.short(),rankingScore:cursor.float(),gameVersion:cursor.varint(),avatar:cursor.string(),cleared:[],fullCombo:[],phi:[]};for(let level=0;level<4;level++){value.cleared.push(cursor.short());value.fullCombo.push(cursor.short());value.phi.push(cursor.short());}return value;}catch(_){return{};}}
  async function parse(zipBytes,playerInfo,saveInfo,catalog){const files=await phigrosZip.read(zipBytes,{maxEntries:64,maxExpandedBytes:32*1024*1024});const summaryData=summary(saveInfo?.summary);const userData=files.has('user')?user(await decrypt(files.get('user'))):{};const progressData=files.has('gameProgress')?progress(await decrypt(files.get('gameProgress'))):{};if(!files.has('gameRecord'))throw new Error('存档中缺少 gameRecord');const chartRecords=records(await decrypt(files.get('gameRecord')),catalog);return{formatVersion:2,profile:{playerId:playerInfo?.nickname||userData.selfIntro||'Phigros Player',objectId:playerInfo?.objectId||'',avatar:userData.avatar||summaryData.avatar||'',background:userData.background||'',selfIntro:userData.selfIntro||'',challengeModeRank:progressData.challengeModeRank||summaryData.challengeModeRank||0,money:progressData.money||[0,0,0,0,0],officialRks:summaryData.rankingScore||0,saveUpdatedAt:saveInfo?.modifiedAt?.iso||saveInfo?.updatedAt||new Date().toISOString(),gameVersion:summaryData.gameVersion||0,cleared:summaryData.cleared||[0,0,0,0],fullCombo:summaryData.fullCombo||[0,0,0,0],phi:summaryData.phi||[0,0,0,0]},records:chartRecords,pushTargets:[]};}
  window.phigrosSaveParser={parse,parseRecords:records,parseSummary:summary};
})();
