import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
globalThis.window=globalThis;
for(const file of ['rks','presentation']) (0,eval)(readFileSync(new URL(`../web/${file}.js`,import.meta.url),'utf8'));
const read=file=>JSON.parse(readFileSync(new URL(`../test/resources/legacy/${file}`,import.meta.url),'utf8'));
const catalog=phigrosPresentation.catalog('id\ttitle\tcomposer\tartist\ta\tb\tc\td\tez\thd\tin\tat\nlow\tLow\t\t\t\t\t\t\t3\t8\t12\nmax\tMax\t\t\t\t\t\t\t4\t9\t15.5\t16.2\nbad\tBad\t\t\t\t\t\t\tNaN');
assert.equal(catalog.length,2);
assert.deepEqual(phigrosPresentation.charts(catalog,new Set(['IN','AT']),'').map(item=>item.constant),[16.2,15.5,12]);
assert.equal(phigrosPresentation.charts(catalog,new Set(['IN']),'low')[0].constant,12);
assert.equal(phigrosPresentation.charts(catalog,new Set(),'').length,0);
const timeline=read('timeline-cn-main.json');
assert.equal(phigrosPresentation.timeline(timeline,30,timeline[0].timestamp+31*86400000).length,0);
assert.equal(phigrosPresentation.timeline(timeline,0,Date.now()).length,timeline.length);
const next={profile:{saveUpdatedAt:'2026-09-16T00:00:00Z',challengeModeRank:523},records:[{id:'new',title:'New',level:'IN',constant:15,accuracy:100,score:1000000,fc:true}]};
const event=phigrosPresentation.historyEvent(null,next,phigrosRks.calculate(next.records));
assert.equal(event.changes[0].tag,'新成绩 · 进入 P3 · 进入 B27');
assert.equal(event.changes[0].oldScore,null);
assert.equal(phigrosPresentation.historyEvent(next,next,phigrosRks.calculate(next.records)).changes.length,0);
const unchanged=phigrosPresentation.historyEvent(next,{...next,profile:{...next.profile,saveUpdatedAt:'2026-09-17T00:00:00Z'}},phigrosRks.calculate(next.records));
const original=[event];
assert.equal(phigrosPresentation.appendHistory(original,unchanged),original);
assert.equal(phigrosPresentation.appendHistory(original,event),original);
assert.equal(phigrosPresentation.timeline([unchanged,event],0).length,1);
assert.equal(phigrosPresentation.appendHistory(original,{...unchanged,newRks:unchanged.newRks+.01}).length,2);
assert.equal(phigrosPresentation.appendHistory(original,{...unchanged,challengeModeRank:524}).length,2);
assert.equal(original.length,1);
const fcBefore={...next,records:[{...next.records[0],score:980000,accuracy:98,fc:false}]};
const fcAfter={...fcBefore,records:[{...fcBefore.records[0],fc:true}]};
const fcEvent=phigrosPresentation.historyEvent(fcBefore,fcAfter,phigrosRks.calculate(fcAfter.records));
assert.equal(phigrosPresentation.meaningfulEvent(fcEvent),true);
assert.equal(phigrosPresentation.grade(next.records[0]),'Phi');
assert.equal(phigrosPresentation.grade({score:950000,fc:false}),'S');
console.log('Phigros presentation: catalog, filters, timeline, history and grade OK');
